{{- if not .Values.secret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alertory.fullname" . }}
  labels:
    {{- include "alertory.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- $data := deepCopy .Values.secret.data }}
  {{- if and .Values.postgresql.enabled (not $data.DATABASE_URL) }}
  {{- $_ := set $data "DATABASE_URL" (include "alertory.postgresqlDatabaseURL" .) }}
  {{- end }}
  {{- range $key, $value := $data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
